services:
  qbittorrent-loadbalancer:
    image: qbittorrent-loadbalancer
    container_name: qbt-loadbalancer
    restart: unless-stopped
    ports:
      # Webhook端口映射
      - "5000:5000"
    volumes:
      # 配置文件挂载
      - ./config.json:/app/config.json:rw
      # 日志目录挂载
      - ./logs:/app/logs:rw
    environment:
      # Python相关环境变量
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      # 可选：通过环境变量覆盖配置
      # - CONFIG_FILE=/app/config.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 