services:
  qbittorrent-loadbalancer:
    image: qbittorrent-loadbalancer
    container_name: qbt-loadbalancer
    restart: unless-stopped
    volumes:
      # 配置文件挂载
      - ./config.json:/app/config.json:rw
      # torrent文件目录挂载
      - ./torrents:/app/torrents:rw
      # 日志目录挂载
      - ./logs:/app/logs:rw
    environment:
      # Python相关环境变量
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      # 可选：通过环境变量覆盖配置
      # - CONFIG_FILE=/app/config.json
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/config.json') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 